### ISSUE TITLE
Bottstrap dependency maximal version 

### ISSUE THREAD

**Issue by mullerch** [cigano/bootstrap-tagsinput#1]
Thanks for your work, it's great !

Why is there a limitation with bootstrap <= 3.3.6, any problems with 3.3.7 ? If not could you update the limitation ? Thanks !

**Comment by rhpot1991** [comment]
I'm guessing jQuery 3 is the limitation here, can anyone confirm?

**Comment by cigano** [comment]
@rhpot1991 Correct. I can update the package to Bootstrap 3.3.7 version.

**Comment by cigano** [comment]
@ozwin I updated the NuGet package to Bootstrap 3.3.7 version, plus restricting jQuery up to version 2.2.4. Please update your project and, if necessary, reopen this issue.

**Comment by mullerch** [comment]
Actually the package requires <3.3.7 (excluded). So the latest possible is 3.3.6.
